#pragma config(Motor,  port2,           passengerFront, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           passengerRear, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           driverFront,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           driverRear,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           liftLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftBLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           liftR,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void remoteControl() {
	motor[driverFront] = motor[driverRear] = vexRT[Ch2];
	motor[passengerFront] = motor[passengerRear] = vexRT[Ch3];

	if (vexRT[Btn6U]) {
		motor[liftLeft] = motor[liftBLeft] = motor[liftR] = 127;
	} else if (vexRT[Btn6D]) {
		motor[liftLeft] = motor[liftBLeft] = motor[liftR] = -127;
	} else {
		motor[liftLeft] = motor[liftBLeft] = motor[liftR] = 0;
	}

	string str = "Average Bat Level: ";
	stringFormat(str, "%1.2f", nAvgBatteryLevel);

	writeDebugStreamLine(str);
}

task main()
{
	while (true) { remoteControl(); }
}
